version: '3.1'

services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: free_ads

  app:
    build:
      dockerfile: ./docker/Dockerfile
      context: .
    ports:
      - 5000:80
    depends_on:
      - "db"
    env_file:
      - .env
    volumes:
      - ./:/var/www/html/

  adminer:
    image: adminer
    ports:
      - 8080:8080