#!/bin/sh
set -e

counter=0
until php artisan migrate --seed; do
    :;
    if [[ ${counter} -eq 20 ]]; then
        echo "Migration can't be completed";
        break;
    fi
 done

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- apache2-foreground "$@"
fi

exec "$@"
